---
- name: Desplegar Jellyfin con Caddy como proxy inverso usando Docker
  hosts: vps
  become: yes
  tasks:
    - name: Actualizar el sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar dependencias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present

    - name: Crear red Docker
      docker_network:
        name: jellyfin_network

    - name: Crear red para proxy
      docker_network:
        name: proxy_network

    - name: Desplegar Jellyfin
      docker_container:
        name: jellyfin
        image: jellyfin/jellyfin
        state: started
        restart_policy: always
        networks:
          - name: jellyfin_network
          - name: proxy_network
        labels:
          caddy: "true"
          caddy.reverse_proxy: "/ {http://jellyfin:8096}"
        ports:
          - "8096:8096"

    - name: Crear archivo de configuración de Caddy
      copy:
        dest: /etc/caddy/Caddyfile
        content: |
          jellyfin.yesweresysadmin.cat {
            reverse_proxy jellyfin:8096
            tls nalvali057@g.educaand.es
          }
        force: yes

    - name: Desplegar Caddy
      docker_container:
        name: caddy
        image: caddy:latest
        state: started
        restart_policy: always
        networks:
          - name: proxy_network
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /etc/caddy:/etc/caddy
        command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]